# Generated by Django 5.0 on 2024-01-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='air_conditioner_temperature',
            new_name='freezer_status',
        ),
        migrations.AlterField(
            model_name='transport',
            name='nebulizer_status',
            field=models.BooleanField(),
        ),
    ]
